---
- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: '{{gather}}'
  tasks:
  - name: telnet installation
    apt:
      name: '{{pkg}}'
      state: latest

    
